* crio development notes

Package code contains a fixed set of possibly parameterized filter
functions f_1, f_2, ..., f_n.  In preparing for a call to read data
via a crio stream, the package will create crio filter structs wrapped
in external pointers using =crio_make_filter_xp=.  Arguments to 
=crio_make_filter_xp= are as follows:

- a name;

- a filter function pointer (f_k);

- a filter context provided as an SEXP;

The return value is an R external pointer SEXP with tag set to the
name value and pointer set to a newly allocated crio filter.  The
external pointer's protection slot is used to protect the filter
context.  The external pointer will also have a finalizer registered
for it that will free the crio filter structure when the xp is gc'd.

Package code will then pass an SEXP containing the result of something
like =quote(f1 & f2 | (!f3 | f4))= along with an environment with keys
f1, f2, f3, and f4 each mapping to an external pointer as returned by
=crio_make_filter_xp= representing the filter that the user wishes to
use.


* TODO Handle missing filters in R environment error
User could specify bad arguments and we should report a useful error
message.
* TODO Need safety mechanism to ensure filter's match context
The filters assume a particular context structure.  If filters are
shared across packages, one could easily create a situation where a
user specifies incompatible filters for the context supplied by a read
function.  If we want to avoid this, we need some mechanism to
identify the type associated with a context and attach that label to
filter functions.
* TODO Measure some real-world uses to validate approach
* TODO Add name validator for crio filter functions
Make sure filter names are valid R identifiers.  Backticks allowed?
* DONE external pointer API
  CLOSED: [2010-03-23 Tue 15:05]
** Refactor template code
** Add function pointer decl to stubs
* DONE crio AST evaluation [6/6]
  CLOSED: [2010-04-02 Fri 15:16]
- [X] Refactor API for setting filter AST on stream creation ecify a
      CrioNode* when creating a stream that is a list node inting to
      the root of the AST.  stream is responsible for this mory.
      Helper function for single filter case.
- [X] R parsed expression => crio AST
- [X] Modify eval for short-cicuit for AND/OR
- [X] Add fun NOT
- [X] Add constants for list NIL and funs AND, OR, NOT
- [X] Cleanup empty list concept and cons'ing w/ NULL
      (done for now: NIL element is a list cell with two NULL pointers
      and is identified by address (singleton).  But the cons function
      allows you the convenience of saying NULL.
* DONE Add accessor for file pointer to pure crio API
  CLOSED: [2010-04-02 Fri 15:17]
* DONE Add accessor for context to *_xp API
  CLOSED: [2010-04-02 Fri 15:17]
** Memory model
Consider implementing a simple memory pool for list cells and nodes.
This could simplify the handling of out of memory situations and also
improve efficiency by avoiding repeated small calls to malloc when
evaluating the AST in the read loop.



